swagger: '2.0'
info:
  title: Shopping Cart MS API
  version: "0.1"
  description: Shopping Cart MS API
consumes:
  - application/json
produces:
  - application/json
basePath: "/api"
securityDefinitions:
  jwt:
    type: apiKey
    name: Authorization
    in: header
    x-authentication-scheme: Bearer
    x-bearerInfoFunc: app.decode_token
paths:
  /reserve_book:
    post:
      tags: [ Reservation ]
      operationId: app.reserve_book
      parameters:
        - $ref: '#/parameters/reservation_body'
      responses:
        200:
          description: Successfully reserved book!
        404:
          description: Something went wrong
parameters:
  reservation_body:
    name: reservation_body
    description: Reservation parameters
    in: body
    schema:
      required:
        - username
        - book_title
        - no_copies
      properties:
        username:
          type: string
        book_title:
          type: string
        no_copies:
          type: integer